## 1 python基本数据类型

### 1.1decimal模块

In [2]:
a = 4
type(a)

int

In [4]:
a.bit_length()  #有没有超出位数限度

3

In [35]:
#decimal模块
import decimal 
from decimal import Decimal

In [9]:
decimal.getcontext()

Context(prec=28, rounding=ROUND_HALF_EVEN, Emin=-999999, Emax=999999, capitals=1, clamp=0, flags=[], traps=[InvalidOperation, DivisionByZero, Overflow])

In [11]:
a=Decimal(2)/Decimal(7)
a

Decimal('0.2857142857142857142857142857')

In [36]:
decimal.getcontext().prec = 3
a=Decimal(2)/Decimal(7)
a

Decimal('0.286')

### 1.2字符串

In [27]:
s="hellow World!"
type(s)

str

In [25]:
s = s.capitalize()  #首字母大写 保证工作对接
s

'Hellow world!'

In [29]:
s.split()
s

'hellow World!'

In [31]:
s.split()[0]  #按照空格取第一个单词

'hellow'

In [35]:
s.find('hellow')

0

In [33]:
s[5: ]

'w World!'

## 2数据结构

### 2.1 列表

- 有序的可变序列 允许重复元素
- 【】 定义   元素之间用逗号分割
- 支持索引和切片
- 用于存储一组有序的数据 可以存储数字 字符串等

In [66]:
liebiao = ['quant',2,5,7,55,3.7]
liebiao

['quant', 2, 5, 7, 55, 3.7]

In [ ]:
type(liebiao[3])

int

In [59]:
liebiao[0:2]   #采取左闭右开

['quant', 2]

In [67]:
liebiao.insert(1,"fuck")    #动态大小空间 可以进行拓展或缩小
liebiao.remove(55)
liebiao

['quant', 'fuck', 2, 5, 7, 3.7]

 ## 2.2字典

- 无序 键-值对（key-value）  命名因子名称  后面跟相应的收益序列   评价指标根据收益序列计算
- 大括号 定义
- 通过键来查找和修改值 而不是位置
- 常用于表示对象属性 配置信息等

In [39]:
stock = {
    'symbol':'AAPL',
    'name':'Apple Inc.',
    'price':150.25,
    'volume':1000000
}

In [6]:
    print("股票信息")
    print("股票代码",stock['symbol'])
    print("服务名称",stock['name'])
    print("股票价格",stock['price'])
    print("成交量",stock['volume'])

股票信息
股票代码 AAPL
服务名称 Apple Inc.
股票价格 150.25
成交量 1000000

In [7]:
stock['price'] = 155.50
print("股票价格",stock['price'])

股票价格 155.5

In [15]:
#检查字典中是否存在某键
if 'close' in stock:
    print("在")
else:
    print("不在")

不在

In [22]:
#获取字典的键的列表
keys = stock.keys()
print("字典的键：",keys)
#获取字典的值的列表
values = stock.values()
print("字典的值: ",values)

字典的键： dict_keys(['symbol', 'name', 'price', 'volume'])
字典的值:  dict_values(['AAPL', 'Apple Inc.', 155.5, 1000000])

In [24]:
#获取所有的键值对
stock.items()

dict_items([('symbol', 'AAPL'), ('name', 'Apple Inc.'), ('price', 155.5), ('volume', 1000000)])

In [32]:
#遍历键值对
for key,value in stock.items():
    print(key ,":",value )

symbol : AAPL
name : Apple Inc.
price : 155.5
volume : 1000000

In [40]:
#删除某个键值对
del stock["volume"]
print(stock)

{'symbol': 'AAPL', 'name': 'Apple Inc.', 'price': 150.25}

In [8]:
#字典里面套字典
stock_data ={
    'APPL':{
        'name':'Alphabet Inc',
        'price':150.25,
        'volume':1000000
    },
      'GOOGL':{
        'name':'Alphabet Inc.',
        'price':150.25,
        'volume':1000000
    },
    'MSFT':{
        'name':"Microsoft Corporation",
        'price':150.25,
        'volume':1000000
    }
}

print(stock_data)

{'APPL': {'name': 'Alphabet Inc', 'price': 150.25, 'volume': 1000000}, 'GOOGL': {'name': 'Alphabet Inc.', 'price': 150.25, 'volume': 1000000}, 'MSFT': {'name': 'Microsoft Corporation', 'price': 150.25, 'volume': 1000000}}

In [51]:
for key,value in stock_data.items():
    print(key ,":",value)

APPL : {'name': 'Alphabet Inc', 'price': 150.25, 'volume': 1000000}
GOOGL : {'name': 'Alphabet Inc.', 'price': 150.25, 'volume': 1000000}
MSFT : {'name': 'Microsoft Corporation', 'price': 150.25, 'volume': 1000000}

In [26]:
#for symbol ,data in stock_data.items():
        #print(f"股票代码:{symbol}")
        #print(f"股票名称:{data['name']}")
        
for symbol, data in stock_data.items():
    print(f"股票代码:{symbol}")
    for key, value in data.items():
        if key == "name":
            print(f"股票名称:{value}")
        if key == "price":
            print(f"股票价格:{value}")
            print("\n")

股票代码:APPL
股票名称:Alphabet Inc
股票价格:150.25


股票代码:GOOGL
股票名称:Alphabet Inc.
股票价格:150.25


股票代码:MSFT
股票名称:Microsoft Corporation
股票价格:150.25

### 2.3集合（Set）

- 集合是无序的唯一元素集合，不允许重复
- 用大括号 或者set()函数定义 元素之间用逗号分割
- 支持集合操作 并集 交集 差集
- 常用于去重数据 检车成员资格

In [29]:
s=set(['a','c','x','d','d'])
s

{'a', 'c', 'd', 'x'}

In [31]:
t = set(['dd','a','cc'])
t

{'a', 'cc', 'dd'}

In [33]:
s.union(t)  #并集

{'a', 'c', 'cc', 'd', 'dd', 'x'}

In [34]:
s.intersection(t) #交集

{'a'}

In [35]:
s.difference(t) #差集

{'c', 'd', 'x'}

### 2.4栈

- 先进后出 LIFO

In [51]:
# 用列表模拟
stack = []
stack.append(1)
stack.append(2)
stack

[1, 2]

In [52]:
top_element = stack.pop()
# print(f"出栈前的栈：{stack}")
print("栈顶:",top_element)
# print(f"出栈后的栈：{stack}")

栈顶: 2

### 2.5队列

- 运行标准差方差 优化
- 有序的数据结构
- 先进先出
- 可以使用列表或者使用queue模块中的队列类来实现
- 任务调度 广度优先搜索 缓冲

In [54]:
from collections import deque
stack = deque()
stack.append(1)
stack.append(2)
stack

deque([1, 2])

In [4]:
import queue
#创建一个队列 
my_queue = queue.Queue()

In [16]:
#入队操作
my_queue.put(1)
my_queue.put(2)
my_queue.put(3)
my_queue.queue

deque([3, 1, 2, 3, 1, 2, 3])

In [22]:
element = my_queue.get()
element

1

In [23]:
#查看队首元素 
my_queue.queue[0]

2

In [24]:
is_empty = my_queue.empty()
is_empty

False

In [25]:
my_queue.queue

deque([2, 3])

# 3Numpy Pandas常用操作

## 3.1 Numpy 多维数组

- 索引切片  布尔索引 花式索引 
- 高效
- 向量化

In [29]:
import numpy as np
#  创建一个包含股票价格的一维数组
stock_prices = np.array([100.0,105.0,98.0,102.5,99.0])
stock_prices

array([100. , 105. ,  98. , 102.5,  99. ])

In [33]:
# 计算股票价格平均值
average_price = np.mean(stock_prices)
print("平均价格",average_price)

平均价格 100.9

In [ ]:
#计算标准差
import numpy as np
from decimal import getcontext, Decimal


std_dev = np.std(stock_prices)
print("标准差：", std_dev)
print(f"标准差：{std_dev:.2f}")

In [ ]:
import numpy as np
#创建一个二维数组 包含多只股票的价格历史数据
stock_data = np.array([[100.0,105.0,98.0,102.5,99.0],
                     [50.0,52.0,48.0,49.5,51.0],
                     [200.0,198.0,205.0,202.5,199.0]])
stock_data

array([[100. , 105. ,  98. , 102.5,  99. ],
       [ 50. ,  52. ,  48. ,  49.5,  51. ],
       [200. , 198. , 205. , 202.5, 199. ]])

In [ ]:
# 计算每支股票的价格
average_prices= np.mean(stock_data,axis=1)  #横着算
print("每支的股票的价格平均值",average_prices)

每支的股票的价格平均值 [100.9  50.1 200.9]

In [ ]:
average_prices_times= np.mean(stock_data,axis=0)  #数列算平均值
print("每个时间点的股票的价格平均值",average_prices_times)

每个时间点的股票的价格平均值 [116.66666667 118.33333333 117.         118.16666667 116.33333333]

In [ ]:
#向量化操作
#假设有一个包含股票价格的一维数组
prices = np.array([100.0,105.0,98.0,102.5,99.0])
#使用向量化操作计算每日收益率
returns = (prices[1: ] - prices [:-1]) / prices[:-1]
print("每日收益率",returns)

每日收益率 [ 0.05       -0.06666667  0.04591837 -0.03414634]

In [ ]:
prices[1:]

array([105. ,  98. , 102.5,  99. ])

In [ ]:
prices[:-1]

array([100. , 105. ,  98. , 102.5])

In [ ]:
np.ones(5)/5

array([0.2, 0.2, 0.2, 0.2, 0.2])

In [ ]:
#向量化计算5日移动平均线  卷积 每天赋予0.2的加权，累加
moving_average = np.convolve(prices,np.ones(5) / 5,mode = 'valid')
print("5日移动平均线",moving_average)

5日移动平均线 [100.9]

In [ ]:
#向量化计算3日移动平均线 
moving_average = np.convolve(prices,np.ones(3) / 3,mode = 'valid')
print("3日移动平均线",moving_average)

3日移动平均线 [101.         101.83333333  99.83333333]

In [ ]:
prices[1:-1]

array([105. ,  98. , 102.5])

In [ ]:
prices[:-2]

array([100., 105.,  98.])

In [ ]:
prices[2:]

array([ 98. , 102.5,  99. ])

In [ ]:
#向量化操作找到极值点 （最大值和最小值）
peak_indexes = np.where((prices[1:-1] > prices[:-2])& (prices[1:-1]>prices[2:]))[0]+1
valley_indexes = np.where((prices[1:-1] < prices[:-2])& (prices[1:-1] < prices[2:]))[0]+1

print("极大值",peak_indexes)
print("极小值",valley_indexes)

极大值 [1 3]
极小值 [2]

# 4Pandas

- 实盘上还是要用C++
- 在Numpy之上的数据分析库
- 两种数据结构 Series DataFame

- Serires 一维数组 类似于带标签的列表
- DataFrame 二维表格型的数据结构  类似数据库表或Excel表格

In [51]:
import pandas as pd
filepath="E:/OB/projects/DEMO/Knowledge/博一/宽客/python-for-quant/notes/quant/quant class/公开股票数据/finance-charts-apple.csv"
df=pd.read_csv(filepath)
df

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing
3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing
...,...,...,...,...,...,...,...,...,...,...,...
501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing
502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing
503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing
504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing
505,2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000,135.350006,116.203299,127.504333,138.805366,Decreasing

In [5]:
df.head()

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing
3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing

In [6]:
df.tail()

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing
502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing
503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing
504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing
505,2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000,135.350006,116.203299,127.504333,138.805366,Decreasing

In [10]:
prices= df['AAPL.Open']
prices

0      127.489998
1      127.629997
2      128.479996
3      128.619995
4      130.020004
          ...
501    132.460007
502    133.080002
503    133.470001
504    135.520004
505    135.669998
Name: AAPL.Open, Length: 506, dtype: float64

In [11]:
df['mean']=(df['AAPL.Open']+df['AAPL.Close'])/2
df

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction,mean
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing,127.660000
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing,128.174999
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing,128.464996
3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing,129.059998
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing,131.510002
...,...,...,...,...,...,...,...,...,...,...,...,...
501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing,132.290001
502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing,133.184998
503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing,134.245002
504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing,135.514999
505,2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000,135.350006,116.203299,127.504333,138.805366,Decreasing,135.510002

In [23]:
#重命名
new_columns = {'AAPL.Open': 'Open'}
tmp = df.rename(columns= new_columns)
tmp

,Date,Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction,mean
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing,127.660000
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing,128.174999
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing,128.464996
3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing,129.059998
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing,131.510002
...,...,...,...,...,...,...,...,...,...,...,...,...
501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing,132.290001
502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing,133.184998
503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing,134.245002
504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing,135.514999
505,2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000,135.350006,116.203299,127.504333,138.805366,Decreasing,135.510002

In [24]:
#删除
df= df.drop(columns='mean')
df

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing
3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing
...,...,...,...,...,...,...,...,...,...,...,...
501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing
502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing
503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing
504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing
505,2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000,135.350006,116.203299,127.504333,138.805366,Decreasing

In [25]:
#描述性统计 相关性计算
statistics = df.describe()
statistics

,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up
count,506.000000,506.000000,506.000000,506.000000,5.060000e+02,506.000000,506.000000,506.000000,506.000000
mean,112.935000,113.919447,111.942016,112.958340,4.317842e+07,110.459312,107.311385,112.739865,118.168345
std,11.287490,11.251892,11.263687,11.244744,1.985253e+07,10.537529,11.095804,10.595315,10.670752
min,90.000000,91.669998,89.470001,90.339996,1.147590e+07,89.008370,85.508858,94.047166,97.572721
25%,105.482500,106.349999,104.657501,105.672499,2.974240e+07,103.484803,97.011245,104.954875,111.052267
50%,112.889999,114.145001,111.800003,113.025002,3.747460e+07,110.821123,107.351628,112.799750,118.472542
75%,122.267498,123.497500,121.599998,122.179998,5.076395e+07,119.255457,114.812152,121.889416,128.515793
max,135.669998,136.270004,134.839996,135.509995,1.622063e+08,135.509995,127.289258,129.845000,138.805366

In [38]:
#收盘价大于开盘价
filtered_data = df[(df['AAPL.Close'] > df['AAPL.Open']) & (df['AAPL.High']> 132)]
filtered_data

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing
48,2015-04-27,132.309998,133.130005,131.149994,132.649994,96954200,127.539552,123.128271,126.853166,130.578062,Increasing
67,2015-05-22,131.600006,132.970001,131.399994,132.539993,45596000,127.966091,123.959896,128.499167,133.038438,Increasing
69,2015-05-27,130.339996,132.259995,130.050003,132.039993,45833200,127.483346,124.118801,128.405834,132.692866,Increasing
106,2015-07-20,130.970001,132.970001,130.699997,132.070007,58900200,127.512324,121.689204,126.320500,130.951796,Increasing
498,2017-02-07,130.539993,132.089996,130.449997,131.529999,38183800,130.962201,114.297891,122.552833,130.807774,Increasing
499,2017-02-08,131.350006,132.220001,131.220001,132.039993,23004100,131.469994,114.194521,123.197666,132.200812,Increasing
500,2017-02-09,131.649994,132.449997,131.119995,132.419998,28349900,132.419998,114.228408,123.826166,133.423924,Increasing
502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing
503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing

In [41]:
#根据条件筛选
filtered_data = df.loc[df['AAPL.Close'] > df['AAPL.Open'],['AAPL.High','AAPL.Close']]
filtered_data

      AAPL.High  AAPL.Close
0    128.880005  127.830002
1    128.779999  128.720001
3    129.500000  129.500000
4    133.000000  133.000000
7    130.869995  130.419998
..          ...         ...
498  132.089996  131.529999
499  132.220001  132.039993
500  132.449997  132.419998
502  133.820007  133.289993
503  135.089996  135.020004

[277 rows x 2 columns]

In [43]:
# 股票代码设置索引
df = df.set_index('Date')
df

,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
Date,,,,,,,,,,
2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing
2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing
2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing
2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing
2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing
...,...,...,...,...,...,...,...,...,...,...
2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing
2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing
2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing
2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing
2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000,135.350006,116.203299,127.504333,138.805366,Decreasing

In [50]:
#索引恢复
df=df.reset_index()
df

,level_0,index,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction,dae
0,0,0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing,2015-02-17
1,1,1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing,2015-02-18
2,2,2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing,2015-02-19
3,3,3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing,2015-02-20
4,4,4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing,2015-02-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,501,501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing,2017-02-10
502,502,502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing,2017-02-13
503,503,503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing,2017-02-14
504,504,504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing,2017-02-15
505,505,505,2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000,135.350006,116.203299,127.504333,138.805366,Decreasing,2017-02-16

In [47]:
# 转换日期为datatime类型
df['Date'] = pd.to_datetime(df['Date'])
df

,index,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction,dae
0,0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing,2015-02-17
1,1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing,2015-02-18
2,2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing,2015-02-19
3,3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing,2015-02-20
4,4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing,2015-02-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing,2017-02-10
502,502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing,2017-02-13
503,503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing,2017-02-14
504,504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing,2017-02-15
505,505,2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000,135.350006,116.203299,127.504333,138.805366,Decreasing,2017-02-16

In [52]:
#转换日期为字符串
df['Date'] = df['Date'].astype('str')
df

,Date,AAPL.Open,AAPL.High,AAPL.Low,AAPL.Close,AAPL.Volume,AAPL.Adjusted,dn,mavg,up,direction
0,2015-02-17,127.489998,128.880005,126.919998,127.830002,63152400,122.905254,106.741052,117.927667,129.114281,Increasing
1,2015-02-18,127.629997,128.779999,127.449997,128.720001,44891700,123.760965,107.842423,118.940333,130.038244,Increasing
2,2015-02-19,128.479996,129.029999,128.330002,128.449997,37362400,123.501363,108.894245,119.889167,130.884089,Decreasing
3,2015-02-20,128.619995,129.500000,128.050003,129.500000,48948400,124.510914,109.785449,120.763500,131.741551,Increasing
4,2015-02-23,130.020004,133.000000,129.660004,133.000000,70974100,127.876074,110.372516,121.720167,133.067817,Increasing
...,...,...,...,...,...,...,...,...,...,...,...
501,2017-02-10,132.460007,132.940002,132.050003,132.119995,20065500,132.119995,114.494004,124.498666,134.503328,Decreasing
502,2017-02-13,133.080002,133.820007,132.750000,133.289993,23035400,133.289993,114.820798,125.205166,135.589534,Increasing
503,2017-02-14,133.470001,135.089996,133.250000,135.020004,32815500,135.020004,115.175718,125.953499,136.731280,Increasing
504,2017-02-15,135.520004,136.270004,134.619995,135.509995,35501600,135.509995,115.545035,126.723499,137.901963,Decreasing
505,2017-02-16,135.669998,135.899994,134.839996,135.350006,22118000,135.350006,116.203299,127.504333,138.805366,Decreasing

In [53]:
#多文件拼接